### ISSUE TITLE
换行发送信息时，信息不能完全展示

### ISSUE THREAD

**Issue by nicecui** [leancloud/leanchat-ios#125]
发送换行符后，文本自适应出错 

来源：
https://forum.leancloud.cn/t/iphone5s/5472
![f2 cy xmee98 p7- -ju](https://cloud.githubusercontent.com/assets/10130959/12163218/8baef902-b546-11e5-9343-28d45e4f31bd.jpg)

**Comment by wrshi** [comment]
https://github.com/leancloud/leanchat-ios/commit/1b64618b83cf8f10d03d0b4753963f88936885e7

solved.
