### ISSUE TITLE
`Assignment to readonly property` error.

### ISSUE THREAD

**Issue by croath** [leancloud/leanchat-ios#140]
Following the installation guide: 
1. Download zip.
2. Install cocoapods.

Build failed with several errors:

```
leanchat-ios-master/LeanChatLib/Classes/controllers/CDChatRoomVC.m:437:27: Assignment to readonly property
leanchat-ios-master/LeanChatLib/Classes/controllers/CDChatRoomVC.m:441:30: Assignment to readonly property
leanchat-ios-master/LeanChatLib/Classes/controllers/CDChatRoomVC.m:442:36: Assignment to readonly property
leanchat-ios-master/LeanChatLib/Classes/controllers/CDChatRoomVC.m:463:16: Assignment to readonly property
leanchat-ios-master/LeanChatLib/Classes/controllers/CDChatRoomVC.m:512:33: Assignment to readonly property
leanchat-ios-master/LeanChatLib/Classes/controllers/CDChatRoomVC.m:585:24: Assignment to readonly property
```

Thanks for your help.

**Comment by wrshi** [comment]
Hey, thanks for your feedback! Nailed it already.

**Comment by croath** [comment]
Thanks @wrshi ,I've checked https://github.com/leancloud/leanchat-ios/commit/2eda7be10124bea9f7fd97e70835e613dfa18329 ,but is it ok that just deleting the code? 

If you just delete the code there, then how will it work properly while storing failed messages or changing resending status?

**Comment by wrshi** [comment]
Relax :) all the readonly properties will be set and updated automatically in the sdk, you don't need to worry about it now.

**Comment by croath** [comment]
Cool. Thanks!

**Comment by wrshi** [comment]
My pleasure :)
