### ISSUE TITLE
Code Review comments

### ISSUE THREAD

**Issue by jwfing** [leancloud/leanchat-ios#2]
@ufosky

**Comment by lzwjava** [comment]
fixed

应用是激活状态还收到离线消息的话，只可能是普通的推送了，不是 IM 功能的离线消息推送。所以去掉了本地通知。

https://github.com/leancloud/leanchat-ios/commit/a77a1cf94e49100a274a50c92437fa6f006fd07a#diff-de9c7df75b44cf921dee44d982314349R92

@jwfing 
现在这样注册会弹出 username has already been token 的提示。
