### ISSUE TITLE
工程设置需要修改，别人 build 到设备的时候减少出错

### ISSUE THREAD

**Issue by ufosky** [leancloud/leanchat-ios#22]
targets-》LeanChat-》General-》Identity-》Team 改为 None
Project-》LeanChat-》Build Settings-》Code Signing 修改如图
![image](https://cloud.githubusercontent.com/assets/801838/6979468/8e20b2a4-da16-11e4-9849-4db5ad5a5128.png)
targets-》LeanChat-》Build Settings-》Code Signing 修改如图
![image](https://cloud.githubusercontent.com/assets/801838/6979444/2310f672-da16-11e4-8890-8b74d1d89928.png)
targets-》LeanChat-》Build Settings-》Search Paths-》Header Search Paths 删除多余路径
![image](https://cloud.githubusercontent.com/assets/801838/6979554/1213025a-da18-11e4-9bd5-af2ed3c31846.png)
targets-》LeanChat-》Build Settings-》Search Paths-》Library Search Paths 删除多余路径
![image](https://cloud.githubusercontent.com/assets/801838/6979572/5b00a026-da18-11e4-923b-34fd75d00785.png)
已经修改过的值可以选中该项按 delete 键还原成默认值

删除 pods，更新工程设置
![image](https://cloud.githubusercontent.com/assets/801838/6979685/cee28b0c-da19-11e4-8366-71e9540806dc.png)

**Comment by daheli** [comment]
## embedded binaries 绝对路径问题 
![1](https://cloud.githubusercontent.com/assets/6140508/6996395/668e5cac-dbb8-11e4-82d2-c16a7684cd09.png) 
 
 
## LeanChatExample 编译错误,求解
![2](https://cloud.githubusercontent.com/assets/6140508/6996399/8639b5e2-dbb8-11e4-9eba-5c1255c81df2.png)

**Comment by lzwjava** [comment]
关于设置，
https://github.com/leancloud/leanchat-ios/commit/4485c002994fdb0483759240c68ebb14601117ee

目测编译错误是因为没有加某些Framework， @daheli

**Comment by lzwjava** [comment]
fixed all
