### ISSUE TITLE
LeanChatLib中第三方库引用方式

### ISSUE THREAD

**Issue by daheli** [leancloud/leanchat-ios#24]
开发引入工程对MessageDisplayKit或者fmdb等第三库修改过自有代码.
引用第三库由pod管理.
这样LeanChatLib.framework 不要打入过多第三方库.

**Comment by daheli** [comment]
leanchatlib 用的动态链接库，重复引入了 AVOSCloud.framework, AVOSCloudIM.framework

错误信息：
2015-04-10 16:58:50.238 NextChat[18675:857808] *** Terminating app due to uncaught exception 'AVOSCloudIM Exception', reason: 'appId is nil'

https://ticket.avosapps.com/tickets/55277a7ae4b01e374f77dc11/threads

**Comment by lzwjava** [comment]
现在改用静态库了，请更新代码

**Comment by lzwjava** [comment]
项目中途迁移到 Pod 依赖会出一些问题，pod 依赖暂时不会用。
