### ISSUE TITLE
将leanChatLib加入pods管理

### ISSUE THREAD

**Issue by cloud-hot** [leancloud/leanchat-ios#27]
能否将leanchatlib加入pods的repo中，要不这样用起来很不方便

**Comment by daheli** [comment]
![1](https://cloud.githubusercontent.com/assets/6140508/7110637/d0cefb0a-e1e7-11e4-94bf-03d532839ed1.png)
![2](https://cloud.githubusercontent.com/assets/6140508/7110638/d0fef95e-e1e7-11e4-8f4d-db6d052a64a0.png)


```
未加入pod前，与Reachability 重复冲突
```

**Comment by lzwjava** [comment]
https://github.com/leancloud/leanchat-ios/commit/9bd3d4903327f953f6db750f950d7b1281959ff7

Reachablility 冲突已修复。

之前试图转过 Pods，遇到一些棘手的问题。

暂时可以通过修改 类名来避免冲突。

**Comment by daheli** [comment]
![3](https://cloud.githubusercontent.com/assets/6140508/7111296/981733a0-e1f0-11e4-9ff4-06f3f2c54817.png)

**Comment by lzwjava** [comment]
done！ 

```
  pod 'LeanChatLib'
```
