### ISSUE TITLE
关于集成LeanChatLib的步骤

### ISSUE THREAD

**Issue by z1995r** [leancloud/leanchat-ios#29]
http://stackoverflow.com/questions/20065666/lexical-or-preprocessor-issue-facebooksdk-facebooksdk-h-file-not-found

按照步骤走，之后会出现file not found 的 错误，所以看下能不能把这几个步骤加上
设置build setting里header sesarchPath这个步骤。

**Comment by lzwjava** [comment]
![image](https://cloud.githubusercontent.com/assets/5022872/7122231/afbeea78-e24c-11e4-88b1-228db60720a7.png)

你好，加上了 ，估计是资源文件的问题

**Comment by z1995r** [comment]
我的并不是这个问题。
在LeanChatExample中option + 左键 进入 LeanChatLib.h 文件，option + 左键 点 CDIM.h 能进入对应文件夹。
在自己项目中，能进入LeanChatLib.h 文件，option + 左键 点 CDIM.h 不能进入CDIM.h文件（其他的头文件也不行），提升Symbol not Found 。编译会出现CDIM.h file not found 错误。
后来在子项目（LeanChatLib）build setting 里header searchPath 项加入
$(PROJECT_DIR)   后面选recursive
在主项目（自己App） build setting li header searchPath 项加入
$(PROJECT_DIR)/LeanChatLIb 后面选recursive

图片上传失败只能手打

**Comment by z1995r** [comment]
通过上面这样，能在我的项目没有使用LeanChatLIb.h的时候不会出现问题。
在使用LeanChatLib.h后，会出现库的冲突。
本身项目通过CocoaPods添加了messageDisplayKit 库。发现在LeanChatLib Vender文件夹里再次添加了messageDisplayKit库。这样导致了冲突

**Comment by lzwjava** [comment]
用LeanChatLib 的MDK库加行了吧，

MDK 上也有 LeanCloud 通信的例子，可参考

https://github.com/xhzengAIB/MessageDisplayKit/tree/master/Example/MessageDisplayKitLeanchatExample
要么用 LeanChatLib的，要么用上面MDK的 LeanChatExample，这个需要你取舍了。

**Comment by z1995r** [comment]
其他方法一直不行，最后还是用的集成MDK库的方法。谢谢～～～
