### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by yanminhaoren** [leancloud/leanchat-ios#32]
clone 代码下来编译出错，应该是LeanChatLib没有引入进来
![image](https://cloud.githubusercontent.com/assets/5320297/8128244/bef7618e-112f-11e5-951a-af838daee3f0.png)

**Comment by lzwjava** [comment]
pod install 了吗？

**Comment by lzwjava** [comment]
@yanminhaoren 好了吗？

**Comment by yanminhaoren** [comment]
pod install 应该是要添加Podfile文件吧。
