### ISSUE TITLE
LeanChatLib 

### ISSUE THREAD

**Issue by beautiful0night** [leancloud/leanchat-ios#36]
用pod下载的LeanChatLib   版本号：0.1.2    是最新的吗  现在和demo中这个库都不一样 导致有些调用的时候出错

**Comment by lzwjava** [comment]
具体调用错误可以贴出来看看么？

刚也发布了 LeanChatLib 0.1.5 版本，可用

pod 'LeanChatLib', '~> 0.1.5' 来指定版本。改了一个类 CDIM 变成了 CDChatManager ，sorry……稍微全局替换一下即可。

![image](https://cloud.githubusercontent.com/assets/5022872/8369856/a2f2000c-1bf2-11e5-9a10-f348f304f8d3.png)

**Comment by lzwjava** [comment]
@beautiful0night 还有问题吗？

**Comment by beautiful0night** [comment]
是的 还有问题 就是现在我pod 导入LeanChatLib 之后   运行项目的时候 会直接报错
dyld: Symbol not found: _OBJC_CLASS_$_AVIMAudioMessage
  Referenced from: /Users/lee/Library/Developer/CoreSimulator/Devices/852FB682-F08F-4132-BAC9-CAA9EA9DCB49/data/Containers/Bundle/Application/3697338B-0712-4F74-822C-1CBA4E0099CF/XinwsDoctor.app/XinwsDoctor
  Expected in: flat namespace
 in /Users/lee/Library/Developer/CoreSimulator/Devices/852FB682-F08F-4132-BAC9-CAA9EA9DCB49/data/Containers/Bundle/Application/3697338B-0712-4F74-822C-1CBA4E0099CF/XinwsDoctor.app/XinwsDoctor

**Comment by lzwjava** [comment]
对，这个我刚刚试了试，也是发现这个，已修正，请把 version 改为 

pod 'LeanChatLib', '0.1.6'

**Comment by lzwjava** [comment]
原来的问题在于 LeanChatLib 是用 pod 'AVOSCloud' ,'~> 3.1.2.4' 引入的，后来sdk更新到了 3.1.2.5 ，LeanChatLib 项目的sdk 便自动升级到了 3.1.2.5 ，和 LeanChat 项目 SDK 版本不同导致了错误。我猜可能是 pod 发现版本不一样，动态依赖进来了。

后来 改了 pod 'AVOSCloud' ,'3.1.2.4'  。指定版本，让它不自动升级。就好了。然后发布了 0.1.6。

参考了 https://guides.cocoapods.org/using/the-podfile.html

**Comment by beautiful0night** [comment]
0.1.6版本可以下载了吗  我pod search的还是只有0.1.5的
