### ISSUE TITLE
Pod install 错误

### ISSUE THREAD

**Issue by hqman** [leancloud/leanchat-ios#38]
[!] Unable to satisfy the following requirements:

- `AVOSCloud (= 3.1.2.6)` required by `Podfile`
- `AVOSCloud (= 3.1.2.6)` required by `Podfile`

**Comment by lzwjava** [comment]
不加 --no-repo-update 试试？

**Comment by lzwjava** [comment]
@hqman 现在跑起来了吗？

**Comment by hqman** [comment]
@lzwjava 可以了 谢谢
