### ISSUE TITLE
消息、添加好友提示几手机震动

### ISSUE THREAD

**Issue by poundswu** [leancloud/leanchat-ios#39]

**Comment by lzwjava** [comment]
添加好友的时候会触发推送，已添加。

**Comment by lzwjava** [comment]
消息的震动见 https://github.com/leancloud/leanchat-ios/issues/40

**Comment by lzwjava** [comment]
我添加了声音，https://github.com/leancloud/leanchat-ios/commit/0ada989557bf66884c4a49d9f42456011f04fc0c

要不试试 @poundswu

**Comment by lzwjava** [comment]
加上了振动，https://github.com/leancloud/leanchat-ios/commit/e6a10409805c74576e1868143ba1adfff33b38eb
