### ISSUE TITLE
离线下的聊天消息推送功能

### ISSUE THREAD

**Issue by poundswu** [leancloud/leanchat-ios#40]
测试了下发现离线下的聊天消息并没有推送到对方的app，是离线下的消息推送功能没实作吗？

**Comment by lzwjava** [comment]
默认使用了生产证书去推送。线上版本可以收到。https://itunes.apple.com/gb/app/leanchat/id943324553

**Comment by poundswu** [comment]
假如我开发版要测试的话，在哪里可以改动啊？

**Comment by lzwjava** [comment]
先看看这个 https://leancloud.cn/docs/realtime_v2.html#聊天离线时可以推送吗_

**Comment by lzwjava** [comment]
所以我只要把这行取消注释就行，

https://github.com/leancloud/leanchat-cloudcode/blob/master/cloud/mchat.js#L20

原理是这样的。每次服务端检查到对方不在线的时候，应该推送给对方的时候，会去调用云代码(就是一堆nodejs代码，需要上传到LeanCloud)的函数，在那个函数里可以配置推送详情。

**Comment by lzwjava** [comment]
或者，直接在管理台配置一下，下面的地方加上，"_profile": "dev"

![image](https://cloud.githubusercontent.com/assets/5022872/8431210/83a825de-1f6a-11e5-99aa-a6dae3912df8.png)

**Comment by poundswu** [comment]
https://github.com/hellojammy/leanchat-cloudcode
谢回复！这个界面推送我试过，是不是类似这里的云端代码部署起来，就可以完成这个功能了？

**Comment by lzwjava** [comment]
不一定。看你的需求。弄这个云代码，只是为了推送的时候信息更友好， “lzwjava:哈哈” 这样。如果仅仅是“您有一条新的消息”。推荐用 管理台来弄。因为那样比较简单，代价小。

**Comment by lzwjava** [comment]
像QQ 就是 “您有一条新的消息”，微信的话，是可以设置是否显示详情的。

这里用“您有一条新的消息”，还考虑到隐私的问题。比如在锁屏页面，你的女朋友在旁边，然后另外一个女生给你发了一条消息。

**Comment by poundswu** [comment]
谢啦，我两种都试一下好了

**Comment by hqman** [comment]
请问 是否支持 第三方平台  发离线消息推送? 比如推送用了 信鸽, 服务端代码如何调用对应接口

**Comment by lzwjava** [comment]
https://leancloud.cn/docs/realtime_v2.html#云引擎_Hook

_receiversOffline
消息发送完成，存在离线的收件人。

这个接口获取消息和接受者，调用信鸽的推送。

**Comment by lzwjava** [comment]
@hqman 其实两者是不违背的。IM 的推送归IM，普通的推送其它来负责。这样也更简单。
