### ISSUE TITLE
关于Badge问题

### ISSUE THREAD

**Issue by poundswu** [leancloud/leanchat-ios#43]
程序在进入时会清空badge，并且把清空的结果save到server。可是实际上假如用户有3条未读信息，然后在打开后还是不去读的话，程序内消息的标签页Badge会是未读信息数，也就是3。可是AppIconBadge就总是会在打开后变成0，尽管实际上有3条未读。此时如果用户离线，在接单离线消息推送时，AppIconBadge会变成0+1=1，可是实际上未读消息数是3+1=4条。

**Comment by lzwjava** [comment]
好的，确实有这个问题。

**Comment by lzwjava** [comment]
@poundswu 你有兴趣弄一下吗？

```
        AVInstallation *currentInstallation = [AVInstallation currentInstallation];
        [currentInstallation setBadge:0];
        [currentInstallation saveInBackgroundWithBlock: ^(BOOL succeeded, NSError *error) {
            NSLog(@"%@", error ? error : @"succeed");
        }];
```

这样来设定 服务端的badge 数。
只要本地未读数有变化的话，就调用上面的代码设置一下。同时设置一下本地的，
```objc
application.applicationIconBadgeNumber = 0;
```

CDChatListVC 里面有 totalUnreadCount。在这里维护一个 totalUnreadCount 变量。当每次 viewDidAppear 的时候，查一下当前的totalUnreadCount，如果和上次的有变化，就用上面的代码设置一下服务器和本地的badge。

有兴趣搞下吗？
Thanks！

**Comment by poundswu** [comment]
OK I'll try
