### ISSUE TITLE
发送失败的消息存储方案

### ISSUE THREAD

**Issue by lzwjava** [leancloud/leanchat-ios#53]
打算在 LeanChat 中支持消息发送失败。目前因为sdk 的消息缓存不存储失败的消息，所以只能自己存储。

有以下思路：

* 新建一个表 ，保存每个对话失败的消息。(message, convid) 
* 每次进入聊天的时候，发现如果聊天连通，则把失败的消息发送出去。如果不通，则显示在列表后面。
* 重发的时候，如果重发成功，则消除表里的记录。失败则不做操作。
* 发送消息的时候，如果发送失败，则往失败的消息表里存一条记录。

有没好的建议。

@tang3w

**Comment by lzwjava** [comment]
之所以考虑到

**发现如果聊天连通，则把失败的消息发送出去。**

这样赶紧把失败的消息处理掉，是因为失败的消息若夹在历史消息列表的话，不太好处理。

**Comment by tang3w** [comment]
挺好的想法，就自动重发吧。

**Comment by lzwjava** [comment]
文件消息还需要测试。

**Comment by lzwjava** [comment]
done

**Comment by lzwjava** [comment]
因为 attachFilePath 也会被序列化，所以重发文件消息没有问题。
