### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by zengchao** [leancloud/leanchat-ios#65]
1.Definition of AVObject must be imported from module LeanChatLib.CDChatListVC before it is required
2.Cannot find protocol definition for AVSubclassing

**Comment by lzwjava** [comment]
https://github.com/leancloud/leanchat-ios#运行

看这里，执行一个 Clean Build Folder 操作即可。快捷键 Option + Shift +Command + K

**Comment by lzwjava** [comment]
@zengchao 可以运行了吗？
