### ISSUE TITLE
使用xcode6.4编译会发生“Parse issue Expected a type”错误

### ISSUE THREAD

**Issue by hxgqh** [leancloud/leanchat-ios#78]
需要在LeanChat-Prefix.pch里面加上一行：
`#import <AVOSCloudIM/AVIMConversation.h>`

**Comment by lzwjava** [comment]
@hxgqh 上面这样修复吗？

**Comment by lzwjava** [comment]
一般 [clean build folder](https://cloud.githubusercontent.com/assets/5022872/9230256/cf822fe4-4153-11e5-876d-ed819babad89.gif) 可以修复这个错误。

之前因为

```
#import <AVOSCloudIM/AVIMConversation.h>
````

直接打的话会看识别不了：
#import <AVOSCloudIM/AVIMConversation.h>

所以上面修复错了。试试 Clean Build folder 吧。
