### ISSUE TITLE
导入3.1.3.1的sdk 运行崩溃的问题

### ISSUE THREAD

**Issue by beautiful0night** [leancloud/leanchat-ios#79]
'AVIMNotSubclassException', reason: 'Class does not conform AVIMTypedMessageSubclassing protocol.'

**Comment by lzwjava** [comment]
能给出更详细的信息吗？

具体哪段代码？能加个断点看看哪里崩溃吗？

**Comment by beautiful0night** [comment]
![da5582ba-ef72-455a-a662-05cd9e11e47c](https://cloud.githubusercontent.com/assets/1849223/9217318/9ea7c722-40f8-11e5-8b2a-1f309222c51c.png)

**Comment by lzwjava** [comment]
具体是 在 init 的时候报错的

```
- (instancetype)init {
    if (![self conformsToProtocol:@protocol(AVIMTypedMessageSubclassing)]) {
        [NSException raise:@"AVIMNotSubclassException" format:@"Class does not conform AVIMTypedMessageSubclassing protocol."];
    }
    if ((self = [super init])) {
        self.mediaType = [[self class] classMediaType];
    }
    return self;
}
```

应该你是有一个自定义的AVIMTypedMessage类，没有遵守 `AVIMTypedMessageSubclassing` 协议。

**Comment by beautiful0night** [comment]
但是我没有自定义AVIMTypedMessage类，可以通过clientId获取历史聊天记录吗

**Comment by lzwjava** [comment]
@beautiful0night 展开 objects 看看每条消息的消息类型，有没有一些奇怪的消息类型。

REST API 支持获取来自某人的消息记录，https://leancloud.cn/docs/realtime_rest_api.html#获取聊天记录

**Comment by lzwjava** [comment]
@beautiful0night 解决了吗？
