### ISSUE TITLE
使用 git submodule 方式集成 LeanChatLib master 分支失败

### ISSUE THREAD

**Issue by AustinChou** [leancloud/leanchat-ios#82]
目前的 HEAD 为 e6c5da3ebc5e5b4f05da8e8084edaf9155660733

我首先使用了 git submodule add，将整个项目克隆到了某个文件夹，然后进入文件夹中的 LeanChatLib，将整个 LeanChatLib 拖入到我要集成的工程文件中，再在这个文件夹下运行 pod install 安装了依赖库，Build Targets 里看到了 LeanChatLib，同时也 Build 成功了。但是在我的 Target （这里称为ABC）中添加了 LeanChatLib 的依赖后，ABC Build 失败，失败信息为：

```
... LeanChatLib.framework/Headers/CDChatListVC.h:9:9: error: include of non-modular header inside framework module 'LeanChatLib.CDChatListVC' [-Werror,-Wnon-modular-include-in-framework-module]
```

更改 Project 设置中的 Allow Non-modular Includes in Framework Modules 为 YES 后解决了此处的 Error，但是 Build 提示：

```
'LeanChatLib/CDUserModle.h' file not found
```

请问一下如何集成 LeanChatLib 到自己的项目中，谢谢。

**Comment by lzwjava** [comment]
请问你的项目是不是没用 pod 。

见[这里](https://github.com/leancloud/leanchat-ios#leanchatlib-介绍)

没用pod 需要配置不少 framework

**Comment by AustinChou** [comment]
是用了 CocoaPods 的，目前按照了 https://ticket.leancloud.cn/tickets/7666 最后一条的方法三，没有问题。

**Comment by lzwjava** [comment]
:+1: 指定 path 就行了。

**Comment by AustinChou** [comment]
对，相对来说改起来也比较方便。
顺便赞一下这个项目，很方便！
