### ISSUE TITLE
收不到推送

### ISSUE THREAD

**Issue by guoyibin27** [leancloud/leanchat-ios#84]
我有两个app，一个user client，一个service client，两个用的是一个lean cloud app id和key，在控制台也上传了自定义的p12文件。通过平台可以推送消息到两个客户端。现在有一个client退到后台，另一个给发消息，另个收不到推送通知，请问如何设置？

**Comment by lzwjava** [comment]
@guoyibin27 具体 appId 能发到我邮件吗？ lzwjava@gmail.com

**Comment by lzwjava** [comment]
已解决。

一开始 clientId 为 servicer-37，聊天是支持的，但离线推送不支持，改为了下划线形式 servicer_37 就行了。

在用 servicer-37 openClient 的时候会报错，如下：

{"code":112,"error":"Invalid channel name. A channel name is either an empty string (the broadcast channel) or contains only a-zA-Z0-9_ or chinese characters and starts with a letter."}

这个应该显示给开发者得知。
