### ISSUE TITLE
iOS9中，进入CDChatRoomVC后，再返回报错

### ISSUE THREAD

**Issue by guoyibin27** [leancloud/leanchat-ios#85]
错误原因
objc[598]: Cannot form weak reference to instance (0x1461a600) of class XHShareMenuView. It is possible that this object was over-released, or is in the process of deallocation.

**Comment by lzwjava** [comment]
https://github.com/leancloud/leanchat-ios/commit/35b694c001d535d03c12e78b780f7f07e0fced03

Fixed

**Comment by lenvonsam** [comment]
how to fixed this bug

**Comment by lzwjava** [comment]
https://github.com/leancloud/leanchat-ios/commit/35b694c001d535d03c12e78b780f7f07e0fced03#diff-ac3b7d19c21dc92311506c673ac59898L213

我去掉了这行，
self.shareMenuScrollView.delegate = self;

具体原因不清楚。

似乎是 当运行到 XHShareMenuView dealloc 的时候，正在释放 shareMenuScrollView。这时去访问它就报错了。

**Comment by lenvonsam** [comment]
![image](https://cloud.githubusercontent.com/assets/10168476/10041464/0282433c-6217-11e5-8a90-a39a196387c0.png)
我已经删除了还是报以下错误
![image](https://cloud.githubusercontent.com/assets/10168476/10041478/1970d23e-6217-11e5-99ad-fd50ef618cb9.png)

**Comment by lenvonsam** [comment]
插件更新到3.1.4之后就自动消失了，还是有错误

**Comment by gujian** [comment]
感觉http://www.jianshu.com/p/841f60876180可以解释这个问题产生的原因
