### ISSUE TITLE
how to convert to swift

### ISSUE THREAD

**Issue by lenvonsam** [leancloud/leanchat-ios#86]
this  example how to convert to swift,in other words , can you provide a swift version

**Comment by lzwjava** [comment]
https://github.com/yahoojapan/objc2swift

这个工具还挺好用的。但需要一个文件一个文件替换。同时转换过程会有一些错误。需要手动修复。

我建议参考 https://github.com/pgbo/WukongSNS

上面有用到这个 IM framework。
