### ISSUE TITLE
升级 Pods 后出现 Undefined symbols for architecture

### ISSUE THREAD

**Issue by AustinChou** [leancloud/leanchat-ios#87]
之前 0.2.4 版本采用 submodule 克隆 leanchat-iOS 项目并以 pod 'LeanChatLib', :path => 'Vendor/leanchat-ios' 导入项目，今天在执行 submodule update 操作的时候，将此项目升级到了 0.2.6，随即编译出现了问题。编译器提示 Undefined symbols for architecture x86_64，我看了一下都是 `_OBJC_CLASS_$_ABC` 类型的 Error，后面的ABC，例如 AVUser 等 AVOSCloud 库内的 Class。

我尝试编译了 submodule 里本项目下的 LeanChat，发现没有问题，然后我就在找 xcodeproj 和 xcworkspace 中设置的差异，发现只有 Other Linker Flags 里面多了 `-Objc -undefined dynamic_lookup`。加入之后编译通过（因为这两个参数的作用），但是一运行就发生 Crash。问题是 `dyld: Symbol not found: _OBJC_CLASS_$_AVCloud`

我想请教一下，LeanChat 项目需要什么特殊配置么？

0.2.4 版本没有任何问题是因为 Pods 里面有 AVOSCloud 和 AVOSCloudIM 两个 Target，可以通过 #import <AVOSCloud/AVOSCloud.h> 正常引入 AVOSCloud 和 AVOSCloudIM 相关代码，但是升级之后就没有了，不清楚是不是和这个也有关系。

**Comment by lzwjava** [comment]
0.2.6 用了 最新的sdk 3.1.4，估计是因为你本地没有这个库导致的。

这样，进入 Vendor/leanchat-ios 目录，然后打开 LeanChat 目录，执行 pod update --verbose ，然后打开 LeanChat.xcworkspace ，看看能不能跑。

**Comment by AustinChou** [comment]
测试了一下 LeanChat.xcworkspace 能够正常编译运行，但是我的项目文件还是无法正常编译运行。

**Comment by lzwjava** [comment]
你的项目也需要 pod update ，同步 LeanChatLib 的代码

@AustinChou

**Comment by AustinChou** [comment]
@lzwjava LeanChat pod update --verbose log: http://pastebin.com/E7p6JXh9
My Project pod update --verbose log: http://pastebin.com/qKLrpKjd

**Comment by lzwjava** [comment]
![image](https://cloud.githubusercontent.com/assets/5022872/10068851/7ade39da-62da-11e5-9186-2562e3f519ff.png)

你项目有这个么

**Comment by AustinChou** [comment]
![qq20150924-0](https://cloud.githubusercontent.com/assets/4608342/10068873/b26b1594-62da-11e5-8513-246e0a7905da.png)

有

**Comment by AustinChou** [comment]
目前我这边找到的问题就是 在 Pods-LeanChat.debug.xcconfig 下的 OTHER_LDFLAGS 里多了 -undefined dynamic_lookup，这个可以使编译通过但是在 Objective-C 载入 Class 的时候导致找不到这个 Class 而 Crash

**Comment by AustinChou** [comment]
@lzwjava Finally I found a workround for this wired problem. This may related to xcworkspace upgrading from old Pods to new Pods. Reference from http://stackoverflow.com/questions/16427421/how-to-remove-cocoapods-from-a-project and do a totally clean re-generation of xcworkspace solved this problem.
