### ISSUE TITLE
(id <CDUserModel> )getUserById:(NSString *)userId 

### ISSUE THREAD

**Issue by zainzy** [leancloud/leanchat-ios#89]
我在getuserByID 这个方法里面,通过userID 查找当前用户的信息, 为什么只要进行查找,就没有结果, 对话框历史消息什么都没有, 也不能发送信息.

**Comment by lzwjava** [comment]
要先实现这个方法：https://github.com/leancloud/leanchat-ios/blob/master/LeanChat/LeanChat/manager/CDIMService.m#L35-L36

你的应用需要提供一个 根据 id 返回 用户信息的逻辑。

先会调用 cacheUserById:

后续调用 getUserById:

因为有些 用户信息你需要从服务器获取。所以提供了 cacheUsersById 的方法。

**Comment by zainzy** [comment]
十分感谢.

**Comment by zainzy** [comment]
不过,需要我的应用提供一个格局id 返回用户信息的逻辑, 这个逻辑我应该在什么地方写呢?

**Comment by zainzy** [comment]
![default](https://cloud.githubusercontent.com/assets/13100049/10959396/f9b179c2-83b2-11e5-951a-e74867bf5fb6.png)
我的是这样的呀,跟你的不同,不知道该咋写了,

**Comment by lzwjava** [comment]
你看看 LeanChat 的实现吧。 https://github.com/leancloud/leanchat-ios/blob/master/LeanChat/LeanChat/manager/CDCacheManager.m#L62

**Comment by zainzy** [comment]
谢谢您

**Comment by zainzy** [comment]
您好,经过您的点拨,我写出了,自己的cache和userManager  能够实现头像和昵称的展示, 可是出现了两个问题,不知道怎么回事,还望赐教:1,发送消息的时候会发送两条, 退出当前页面,再回来就正常了.2.不能刷新聊天记录,往下拉 chatRommVC 就会崩溃  崩溃地方如图所示:
![Uploading 1.jpg…]()

**Comment by zainzy** [comment]
![1](https://cloud.githubusercontent.com/assets/13100049/10991503/cae897b0-8498-11e5-8fd8-787c80411327.jpg)

**Comment by lzwjava** [comment]
这个问题一般是同时多个地方更新 tableView 导致的。

可以在这些地方进行判断，if isLoadingTableView return  else load. 

类似的。
