### ISSUE TITLE
接受好友请求可以多次点击

### ISSUE THREAD

**Issue by hjiang** [leancloud/leanchat-ios#9]
然后会出现「请求已经接受过」的错误。第一次点击后应该界面就不能点击了。

**Comment by hjiang** [comment]
@lzwjava 这个问题还在不在？

**Comment by lzwjava** [comment]
是指申请加好友的时候吗？

![image](https://cloud.githubusercontent.com/assets/5022872/8450291/09dc2744-200c-11e5-9a83-2ef7d5a08a76.png)

**Comment by hjiang** [comment]
我忘了，可能是以前的版本。我先 close 吧。
