### ISSUE TITLE
会话断开，请检查网络

### ISSUE THREAD

**Issue by angus2651** [leancloud/leanchat-ios#91]
退出再进入，总是出现这个信息。

**Comment by ChenYilong** [comment]
近期会修复掉 https://github.com/leancloud/leanchat-ios/issues/95

**Comment by ChenYilong** [comment]
已修复 https://github.com/leancloud/leanchat-ios/pull/96/files

**Comment by hezhao** [comment]
能不能把App Store的版本也更新一下？修复以后的推送只能在App Store版本中体现出来。谢谢！
