### ISSUE TITLE
最新的跑不起来！

### ISSUE THREAD

**Issue by wells1013** [leancloud/leanchat-ios#92]
dyld: Symbol not found: _OBJC_CLASS_$_AVAnalytics
  Referenced from: /Users/wells/Library/Developer/CoreSimulator/Devices/7CF78734-DF11-496A-B028-CD622EE91CE0/data/Containers/Bundle/Application/F05F6378-404F-4B36-8389-993BC44691E2/LeanChat.app/LeanChat
  Expected in: flat namespace
 in /Users/wells/Library/Developer/CoreSimulator/Devices/7CF78734-DF11-496A-B028-CD622EE91CE0/data/Containers/Bundle/Application/F05F6378-404F-4B36-8389-993BC44691E2/LeanChat.app/LeanChat

**Comment by lzwjava** [comment]
要运行 

```
pod install --verbose --no-repo-update
```

打开 LeanChat.xcworkspace
